### ISSUE TITLE
compilation broken on raspberry pi4

### ISSUE THREAD

**Issue by jpelletier** [eclipse-mraa/mraa#1020]
[make.log](https://github.com/eclipse/mraa/files/4642658/make.log)

**Comment by tingleby** [comment]
So the Swig+NodeJS stuff is not in a good shape right now, try adding `-DBUILDSWIGNODE=off` to your cmake

**Comment by jpelletier** [comment]
Compilation completed fine with cmake .. -DBUILDSWIGNODE=off
