### ISSUE TITLE
Nodejs for Up 2 Board: All of GPIO Pins can not be used

### ISSUE THREAD

**Issue by Jianfengusa** [eclipse-mraa/mraa#1069]
Hello, 

I am using Nodejs@4.7.0 on Up 2 Board with mraa@1.0.0, I am having an issue using GPIO pins for output, can anyone help? 

Here are some error info.
![image](https://user-images.githubusercontent.com/31595152/123558768-a2e85e80-d75d-11eb-9c78-fa8b4431f8c9.png)
![image](https://user-images.githubusercontent.com/31595152/123558775-a8de3f80-d75d-11eb-94e6-5e47a262b838.png)

**Comment by Jianfengusa** [comment]
Come on guys, I really need help on this one!!!

**Comment by Propanu** [comment]
Hi @Jianfengusa, upgrade to one of the latest versions of the library and it should detect your platform. UP2 was added in MRAA 1.8. Thanks!

**Comment by Jianfengusa** [comment]
Thank you for the help, I will try it out.

**Comment by Jianfengusa** [comment]
Thank you so much @Propanu, once I upgrade my mraa it works.
