### ISSUE TITLE
Possible support for Adafruit ft232h on Linux x86 desktop

### ISSUE THREAD

**Issue by Petross404** [eclipse-mraa/mraa#1089]
Hi,

I tried to use mraa (it's c++ bindings specifically) for controlling my Adafruit FT232H board and it's gpio pins but without success. Is this library supposed to work only on embedded arches or can I use it somehow on my x86 Linux for my board?

Thank you for your time.

**Comment by tingleby** [comment]
This library typically runs on Linux platforms x86/arm/mips with the IO being provided by the SoC. There is support for these kind of USB break out boards, see https://github.com/eclipse/mraa/blob/master/docs/ftdi_ft4222.md which might be applicable

**Comment by Petross404** [comment]
I see, I didn't know this.

Thank you very much and forgive my delayed answer.
