### ISSUE TITLE
RISC-V linux platform support

### ISSUE THREAD

**Issue by MaoniinoaM** [eclipse-mraa/mraa#1097]
Hi, mraa team,
I try to build MRAA library in a RISCV LINUX platform, VisionFive board.
And it says, "Only x86, arm, mips, PERIPHERALMAN and mock platforms currently supported".

so When will MRAA support RISCV linux platform?

**Comment by MaoniinoaM** [comment]
Or how to modify it to support RISCV quickly?

**Comment by kassane** [comment]
Likewise, it would also be relevant to extend support to other popular socs eg allwinner D1.
